#程序端口
server:
  port: 7878
  ssl:
    key-store: classpath:4155224_www.luckcome.top.pfx
    key-store-type: PKCS12
    key-store-password: sWIJb613
#  ssl:
#    key-password: 123456
#    key-store: classpath:spring.keystore
#    key-alias: spring


#数据源配置
spring:
  datasource:
    name: luck_come
    url: jdbc:mysql://39.106.159.116:3306/luck_come?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/luck_come?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: chenming123
#    password: 123456
    # password: cY+qV/UGnuFJ/qBQDppj++1hxX1buy+NlXWww==    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #filters: stat,config
    filters: stat
    maxActive: 20
    initialSize: 1

    initial-size: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 39.106.159.116
    password: chenming123
    port: 6379
    jedis:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8     #连接池中的最大空闲连接
        min-idle: 1     #连接池中的最小空闲连接
        max-wait: 3000  #连接池最大阻塞等待毫秒时间（使用负值-1表示没有限制）
    jackson:            #关闭json转换的时候空的bean会报异常
      time-zone: GMT+8
      serialization:
        FAIL_ON_EMPTY_BEANS: false
        WRITE_DATES_AS_TIMESTAMPS: true #timestamp对象在序列化时为int
#      date-format: yyyy-MM-dd HH:mm:ss
#      time-zone: GMT+8
#      default-property-inclusion: non_empty


################### beetsql配置 ########################
# 默认是true，即向控制台输出执行时候的sql，参数，执行时间，以及执行的位置，每次修改sql文件的时候，自动检测sql文件修改
beetl-beetlsql:
  dev: true
# sql 文件的位置
beetlsql:
  sqlPath: /sql
  basePackage: com.luck.dataDao
  daoSuffix: Dao
  dbStyle: org.beetl.sql.core.db.MySqlStyle

jwt:
  secret: dfc438ec1d5c4cc50ea6796352edc7f5

token:
  persistSeconds: 86400 #[一个小时] 持续时间，如果没有api持续访问，此时间后token失效
  expiresSeconds: 86400 #[一天] 到期时间，就算一直有api持续访问，此时间后token也会失效

upload:
  path: /uploadFile
